In [47]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [48]:
y_data = [i for i in range(1,101)]
x_data = [y_data[i]*2 + 1 for i in range(0,100)]
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data,test_size = 0.4, random_state=0)
x_train = np.array(x_train)
x_test = np.array(x_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

In [49]:
#weights to minimize squared loss in case of linear model
w1 = ((y_train * x_train).mean() - y_train.mean() * x_train.mean())/((x_train * x_train).mean() - x_train.mean() * x_train.mean())
w0 = y_train.mean() - w1 * x_train.mean()
w0,w1

(-0.5, 0.5)

In [50]:
y_pred = x_test*w1 + w0
y_pred, y_test

(array([ 27.,  87.,   3.,  56.,  76.,  94.,  17.,  74.,  55.,  96.,  54.,
         93.,  79.,  14.,   8.,  31.,  23.,  25.,  34.,   9.,  44.,  63.,
          4.,  72.,  46.,  49.,   7., 100.,  83.,  77.,  61.,  81.,  91.,
         69.,  52.,  28.,  19.,  57.,  64.,  75.]),
 array([ 27,  87,   3,  56,  76,  94,  17,  74,  55,  96,  54,  93,  79,
         14,   8,  31,  23,  25,  34,   9,  44,  63,   4,  72,  46,  49,
          7, 100,  83,  77,  61,  81,  91,  69,  52,  28,  19,  57,  64,
         75]))

In [51]:
#calculating loss
loss = 0
for i in range(len(y_pred)):
    loss += (y_test[i] - y_pred[i])**2
print(loss)

0.0


In [52]:
#trying on a fourth order polynomial
x_data = np.array(x_data)
x_2 = x_data * x_data
x_3 = x_2 * x_data
x_4 = x_3 * x_data
x_data_new = []
for i in range(len(x_data)):
    x_data_new.append([x_data[i],x_2[i],x_3[i],x_4[i]])
x_data_new = np.array(x_data_new)
y_data = np.array(y_data)
x_train,x_test,y_train,y_test = train_test_split(x_data_new,y_data,test_size = 0.4, random_state=0)
y_test

array([ 27,  87,   3,  56,  76,  94,  17,  74,  55,  96,  54,  93,  79,
        14,   8,  31,  23,  25,  34,   9,  44,  63,   4,  72,  46,  49,
         7, 100,  83,  77,  61,  81,  91,  69,  52,  28,  19,  57,  64,
        75])

In [53]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [54]:
w1 = model.coef_[0]
w2 = model.coef_[1]
w3 = model.coef_[2]
w4 = model.coef_[3]
w0 = model.intercept_
print(w1,w2,w3,w4,w0)

0.49999999999999983 8.437948743969273e-18 -8.713307424740716e-20 2.5611873666738825e-22 -0.5000000000000142


In [55]:
print(model.score(x_test,y_test))
loss = 0
for i in range(len(x_test)):
    loss += (y_test[i] - (w0 + w1 * x_test[i][0] + w2 * x_test[i][1] + w3 * x_test[i][2] + w4 * x_test[i][3]))**2
print(loss)

1.0
7.538354810291989e-27


In [56]:
# trying with the third model
a = 1
x_sin = np.sin(x_data - a)
x_data_new2 = []
for i in range(len(x_data)):
    x_data_new2.append([x_data[i],x_sin[i]])
x_train,x_test,y_train,y_test = train_test_split(x_data_new2,y_data,test_size = 0.4, random_state=0)
model2 = LinearRegression()
model2.fit(x_train,y_train)
w1 = model2.coef_[0]
w2 = model2.coef_[1]
w0 = model2.intercept_
print(w1,w2,w0)
print(model2.score(x_test,y_test))
loss = 0
for i in range(len(x_test)):
    loss += (y_test[i] - (w1 * x_test[i][0] + w2 * x_test[i][1] + w0))**2
print(loss)

0.49999999999999994 -2.849128066461316e-16 -0.4999999999999929
1.0
3.4571829171310842e-28
